name: $(Date:yyyyMMddHHmm)-$(Rev:r)

trigger: 
  - release/*

pr: none

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: master
      endpoint: hmcts

pool: 
  vmImage: ubuntu-22.04

#####################################################
# Pre-Release Tasks. ################################
stages:
- stage: Pre_Run_Tasks
  displayName: Pre-Release Tasks
  variables:
  - template: variables/shared.yaml
  jobs:
  - job: Generate_Entity_Framework_Script
    displayName: "Generate Entity Framework Script"
    steps:
    - template: templates/Database/EntityFramework/generate-script.yaml@azTemplates
      parameters:
        outputPath: $(Build.StagingDirectory)
        contextName: ${{ variables.efContextName }}
        workingPath: $(System.DefaultWorkingDirectory)/${{ variables.appName }}/${{ variables.appName }}
        projectName: ${{ variables.efProjectName }}
        migrationsPath: ${{ variables.appName }}/${{ variables.appName }}.DAL/Migrations


#####################################################
# Run Entity Framework Demo. #####################
- stage: Run_Entity_Framework
  displayName: Demo EF Release
  dependsOn:
    - Pre_Run_Tasks
  variables:
  - template: variables/demo.yaml
  - template: variables/shared.yaml
    parameters:
      env: ${{ variables.env }}
  jobs:
  - job: Run_Entity_Framework_Demo
    pool:
      vmImage: 'windows-latest'
    displayName: Run Entity Framework Demo
    steps:
    - download: current
      displayName: Download Sql Artifact

    - template: templates/Azure/Common/unlock-lock.yaml@azTemplates
      parameters:
        addOrDelete: delete
        lockName: "${{ variables.env }}-lock"
        resourceGroup: ${{ variables.vhResourceGroup }}
        azureSubscription: ${{ variables.subscriptionName }}

    - template: templates/Database/EntityFramework/run-entity-framework.yaml@azTemplates
      parameters:
        sqlServerResourceGroup: ${{ variables.vhResourceGroup }}
        sqlServerName: ${{ variables.vhSQLServerName }}
        databaseName: ${{ variables.videoApiDbName }}
        azureSubscription: ${{ variables.subscriptionName }}
        sqlScriptLocation: "$(Pipeline.Workspace)/${{ variables.efContextName }}-$(Build.BuildId)/${{ variables.efContextName }}.sql"
        kvfirewallRequired: false
        kvName: ${{ variables.vhKeyVault }}
        kvSqlPasswordSecret: ${{ variables.vhSqlPasswordSecret }}
        kvSqlUsernameSecret: ${{ variables.vhSqlUsernameSecret }}

    - template: templates/Azure/Common/unlock-lock.yaml@azTemplates
      parameters:
        addOrDelete: add
        lockName: "${{ variables.env }}-lock"
        resourceGroup: ${{ variables.vhResourceGroup }}
        azureSubscription: ${{ variables.subscriptionName }}
        lockType: CanNotDelete

#####################################################
# Publish Nuget Packages. ############################
- stage: Push_Nuget
  displayName: Push Nuget Packages
  dependsOn:
    - Run_Entity_Framework
  variables:
  - template: variables/shared.yaml
    parameters:
      env: ${{ variables.env }}
  jobs: 
  - job: Publish_Nuget
    displayName: Publish NuGet Packages
    steps:
    - template: templates\dotnet\push-nuget-packages.yml@azTemplates
      parameters:
        vstsFeed: "${{ variables.nuget_org_name }}/${{ variables.nuget_feed_name }}"
