name: $(Date:yyyyMMddHHmm)-$(Rev:r)

trigger: 
  - release/*

pr: none

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: master
      endpoint: hmcts

pool: 
  vmImage: ubuntu-22.04
