name: $(Date:yyyyMMddHHmm)-$(Rev:r)

trigger: 
  - release/*

pr: none

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: master
      endpoint: hmcts

pool: 
  vmImage: ubuntu-22.04

#####################################################
# Pre-Release Tasks. ################################
stages:
- stage: Pre_Run_Tasks
  displayName: Pre-Release Tasks
  variables:
  - template: variables/shared.yaml
  jobs:
  - job: Generate_Entity_Framework_Script
    displayName: "Generate Entity Framework Script"
    steps:
    - template: templates/Database/EntityFramework/generate-script.yaml@azTemplates
      parameters:
        outputPath: $(Build.StagingDirectory)
        contextName: ${{ variables.efContextName }}
        workingPath: $(System.DefaultWorkingDirectory)/${{ variables.appName }}/${{ variables.appName }}
        projectName: ${{ variables.efProjectName }}
        migrationsPath: ${{ variables.appName }}/${{ variables.appName }}.DAL/Migrations
  #####################################################
  # Build Docker Image & Push. ########################
- stage: Docker_Build_Push_Prod
  displayName: Docker Build & Push Image
  variables:
  - template: variables/production.yaml
  - template: variables/shared.yaml
  jobs:
      - job: Docker_Build
        displayName: 'Docker Build and Push'
        steps:
          - checkout: self

          - bash: |
              sed -i "s|</configuration>|<packageSourceCredentials><vh-packages><add key=\"Username\" value=\"PAT\" /><add key=\"ClearTextPassword\" value=\"$(System.AccessToken)\" /></vh-packages></packageSourceCredentials></configuration>|" nuget.config
            displayName: Add NuGet Feed Authentication
            workingDirectory: ${{ variables.appName }}

          - template: templates\Containerisation\docker\docker-compose.yaml@azTemplates
            parameters:
              azureSubscription: ${{ variables.acrSubscription }}
              acrName: ${{ variables.acrName }}
              repositoryName: ${{ variables.repositoryName }}

          - template: templates\Containerisation\docker\docker-push-azure.yaml@azTemplates
            parameters:
              azureSubscription: ${{ variables.acrSubscription }}
              acrName: ${{ variables.acrName }}
              repositoryName: ${{ variables.repositoryName }}
              imageName: '${{ variables.imageName }}'
              imageTags:
                - '${{ variables.releaseTagName }}'
                - 'latest'