name: $(Date:yyyyMMddHHmm)-$(Rev:r)

trigger: 
  - release/*

pr: none

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: master
      endpoint: hmcts

pool: 
  vmImage: ubuntu-22.04


#########################################
# Push Helm Charts to Repo. #############
#############
stages:
- stage: Helm_Production
  displayName: Push Helm Charts
  variables:
  - template: variables/production.yaml
  - template: variables/shared.yaml
  - group: vh-github-app-credentials
  jobs:
  - job: Helm
    displayName: "Helm Push"
    steps:
    - checkout: self

    - template: templates\Github\get-app-token.yaml@azTemplates
      parameters:
        privateKeyFileName: ${{ variables.gh_app_private_key_file_name }}
        appId: $(gh_app_app_id)

    - template: templates\Github\push-to-helm-chart-repo.yaml@azTemplates
      parameters:
        chartName: ${{ variables.chartName }}
        chartPath: ${{ variables.chartPath }}
        githubToken: $(githubappinstall.token)
        githubUsername: $(gh_app_name)
        githubEmail: "$(gh_app_app_id)+$(gh_app_name)[bot]@users.noreply.github.com"
        subDirectory: ${{ variables.subDirectory }}

