version: '3.4'

services:
  videoapi:
    image: ${DOCKER_REGISTRY-}videoapi:latest
    build:
      context: .
      dockerfile: VideoApi/VideoApi/Dockerfile

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000"
    ports:
      - "10000:10000"
