using Microsoft.EntityFrameworkCore.Migrations;

namespace VideoApi.DAL.Migrations
{
    public partial class UpdateFirstLastNames : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom5' WHERE Username = 'ManchesterCFJCcourt5@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom6' WHERE Username = 'ManchesterCFJCcourt6@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom7' WHERE Username = 'ManchesterCFJCcourt7@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom8' WHERE Username = 'ManchesterCFJCcourt8@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom9' WHERE Username = 'ManchesterCFJCcourt9@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom10' WHERE Username = 'ManchesterCFJCcourt10@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom11' WHERE Username = 'ManchesterCFJCcourt11@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom12' WHERE Username = 'ManchesterCFJCcourt12@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom13' WHERE Username = 'ManchesterCFJCcourt13@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom14' WHERE Username = 'ManchesterCFJCcourt14@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom15' WHERE Username = 'ManchesterCFJCcourt15@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom16' WHERE Username = 'ManchesterCFJCcourt16@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom17' WHERE Username = 'ManchesterCFJCcourt17@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom18' WHERE Username = 'ManchesterCFJCcourt18@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom19' WHERE Username = 'ManchesterCFJCcourt19@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom20' WHERE Username = 'ManchesterCFJCcourt20@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom21' WHERE Username = 'ManchesterCFJCcourt21@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom22' WHERE Username = 'ManchesterCFJCcourt22@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom23' WHERE Username = 'ManchesterCFJCcourt23@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom24' WHERE Username = 'ManchesterCFJCcourt24@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Courtroom25' WHERE Username = 'ManchesterCFJCcourt25@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'DDJretiringroom' WHERE Username = 'ManchesterCFJCDDJretiringroom@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'CourtGen1' WHERE Username = 'ManchesterCFJCcourtGen1@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'CourtGen2' WHERE Username = 'ManchesterCFJCcourtGen2@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'CourtGen3' WHERE Username = 'ManchesterCFJCcourtGen3@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Judge' WHERE Username = 'ManchesterCJC.Judge@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Manchester CFJC', LastName = 'Judge2' WHERE Username = 'ManchesterCJC.Judge2@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'Courtroom114' WHERE Username = 'BirminghamCFJCcourt114@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'Courtroom115' WHERE Username = 'BirminghamCFJCcourt115@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'Courtroom116' WHERE Username = 'BirminghamCFJCcourt116@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'Courtroom117' WHERE Username = 'BirminghamCFJCcourt117@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'Courtroom118' WHERE Username = 'BirminghamCFJCcourt118@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'Courtroom119' WHERE Username = 'BirminghamCFJCcourt119@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'Courtroom121' WHERE Username = 'BirminghamCFJCcourt121@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'Courtroom199' WHERE Username = 'BirminghamCFJCcourt199@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'CourtGen1' WHERE Username = 'BirminghamCFJCcourtGen1@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'CourtGen2' WHERE Username = 'BirminghamCFJCcourtGen2@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'CourtGen3' WHERE Username = 'BirminghamCFJCcourtGen3@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'Judge' WHERE Username = 'BirminghamCJC.Judge@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Birmingham CFJC', LastName = 'Judge2' WHERE Username = 'BirminghamCJC.Judge2@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Taylor House', LastName = 'Courtroom28' WHERE Username = 'TaylorHousecourt28@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Taylor House', LastName = 'Courtroom29' WHERE Username = 'TaylorHousecourt29@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Taylor House', LastName = 'Courtroom30' WHERE Username = 'TaylorHousecourt30@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Taylor House', LastName = 'Courtroom31' WHERE Username = 'TaylorHousecourt31@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Taylor House', LastName = 'Courtroom32' WHERE Username = 'TaylorHousecourt32@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Taylor House', LastName = 'Courtroom33' WHERE Username = 'TaylorHousecourt33@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Taylor House', LastName = 'CourtroomGen1' WHERE Username = 'TaylorHousecourtGen1@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Taylor House', LastName = 'CourtroomGen2' WHERE Username = 'TaylorHousecourtGen2@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Taylor House', LastName = 'CourtroomGen3' WHERE Username = 'TaylorHousecourtGen3@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Taylor House', LastName = 'CourtroomGen4' WHERE Username = 'TaylorHousecourtGen4@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Taylor House', LastName = 'CourtroomGen5' WHERE Username = 'TaylorHousecourtGen5@hearings.reform.hmcts.net'
                Update Participant set FirstName = 'Taylor House', LastName = 'CourtroomGen6' WHERE Username = 'TaylorHousecourtGen6@hearings.reform.hmcts.net'
                ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt5@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt6@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt7@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt8@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt9@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt10@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt11@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt12@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt13@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt14@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt15@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt16@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt17@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt18@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt19@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt20@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt21@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt22@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt23@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt24@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourt25@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCDDJretiringroom@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourtGen1@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourtGen2@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCFJCcourtGen3@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCJC.Judge@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'ManchesterCJC.Judge2@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCFJCcourt114@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCFJCcourt115@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCFJCcourt116@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCFJCcourt117@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCFJCcourt118@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCFJCcourt119@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCFJCcourt121@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCFJCcourt199@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCFJCcourtGen1@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCFJCcourtGen2@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCFJCcourtGen3@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCJC.Judge@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'BirminghamCJC.Judge2@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'TaylorHousecourt28@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'TaylorHousecourt29@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'TaylorHousecourt30@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'TaylorHousecourt31@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'TaylorHousecourt32@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'TaylorHousecourt33@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'TaylorHousecourtGen1@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'TaylorHousecourtGen2@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'TaylorHousecourtGen3@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'TaylorHousecourtGen4@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'TaylorHousecourtGen5@hearings.reform.hmcts.net'
                Update Participant set FirstName = NULL, LastName = NULL WHERE Username = 'TaylorHousecourtGen6@hearings.reform.hmcts.net'
                ");
        }
    }
}
