---
java:
  image: '${IMAGE_NAME}'
  ingressHost: ${SERVICE_FQDN}
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    SERVICES__VIDEOAPIRESOURCEID: http://vh-video-api.staging.platform.hmcts.net

