---
java:
  image: '${IMAGE_NAME}'
  ingressHost: ${SERVICE_FQDN}
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    SERVICES__CALLBACKURI:  https://vh-video-web-pr-2171.dev.platform.hmcts.net/callback