---
java:
  image: '${IMAGE_NAME}'
  ingressHost: ${SERVICE_FQDN}
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    KINLYCONFIGURATION__CALLBACKURI: https://vh-video-web-pr-2318.dev.platform.hmcts.net/callback
    VODAFONECONFIGURATION__CALLBACKURI: https://vh-video-web-pr-2318.dev.platform.hmcts.net/callback
    SERVICES__CALLBACKURI: https://vh-video-web-pr-2318.dev.platform.hmcts.net/callback